blank_issues_enabled: false
contact_links:
    - name: Discussions
      url: https://github.com/Darkflame72/defectio/discussions
      about: A perfect place to ask questions and get help with issues you are having.
    - name: Revolt server
      url: https://app.revolt.chat/invite/FfbwgFDk
      about: Joining our Revolt server is an ideal way to ask questions, contact the maintainers, stay up to date with updates and get to know other developers.
